spring.application.name=shipping-estimator
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.show-sql=false 
spring.datasource.hikari.maximum-pool-size=10
spring.sql.init.mode=always
management.endpoints.web.exposure.include=mappings,health,info
